os: linux

sudo: required

language: python

cache: pip

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo docker run -e MYSQL_ROOT_PASSWORD=first1208 -d -p 7000:3306 mysql

install:
  - pip3 install -r requirements.txt
  - pip install codecov pytest-cov

script:
  - pytest --cov=./

before_script:
  - cd Server

after_success:
   - codecov