os: linux

sudo: required

language: python

cache: pip

services:
  - mysql

python:
  - "3.5"
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip install codecov pytest-cov

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('first1208') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sudo service mysql restart
  - mysql -uroot -pfirst1208 -e 'CREATE DATABASE IF NOT EXISTS entry;'
  - cd Server

script:
  - pytest --cov=./

after_success:
   - codecov