-- MySQL Script generated by MySQL Workbench
-- Tue Sep 11 20:20:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema entry
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `entry` ;

-- -----------------------------------------------------
-- Schema entry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entry` DEFAULT CHARACTER SET utf8 ;
USE `entry` ;

-- -----------------------------------------------------
-- Table `entry`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`admin` (
  `admin_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `admin_type` ENUM('ROOT', 'ADMINISTRATION', 'QNA', 'INTERVIEW') NOT NULL DEFAULT 'INTERVIEW',
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`user` (
  `user_id` VARCHAR(32) NOT NULL,
  `additional_type` ENUM('NONE', 'NATIONAL_MERIT', 'SPECIAL_ADMISSION') NOT NULL DEFAULT 'NONE',
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `graduate_type` ENUM('WILL', 'DONE', 'GED') NOT NULL DEFAULT 'WILL',
  `admission` ENUM('NORMAL', 'MEISTER', 'SOCIAL') NOT NULL DEFAULT 'NORMAL',
  `admission_detail` ENUM('NONE', 'BENEFICIARY', 'ONE_PARENT', 'CHA_UPPER', 'CHACHA_UPPER', 'FROM_NORTH', 'MULTI_CULTURE', 'ETC') NOT NULL DEFAULT 'NONE',
  `region` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_user_email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`apply_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`apply_status` (
  `user_id` VARCHAR(32) NOT NULL,
  `final_submit` TINYINT(1) NOT NULL DEFAULT '0',
  `pass_status` TINYINT(1) NOT NULL DEFAULT '0',
  `payment` TINYINT(1) NOT NULL DEFAULT '0',
  `receipt` TINYINT(1) NOT NULL DEFAULT '0',
  `receipt_code` INT(3) ZEROFILL NOT NULL AUTO_INCREMENT,
  `exam_code` VARCHAR(6) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `receipt_code_UNIQUE` (`receipt_code` ASC),
  UNIQUE INDEX `exam_code_UNIQUE` (`exam_code` ASC), 
  CONSTRAINT `FK_apply_status_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`document` (
  `user_id` VARCHAR(32) NOT NULL,
  `introduce` VARCHAR(1600) NOT NULL DEFAULT '',
  `study_plan` VARCHAR(1600) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK_document_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`ged_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`ged_score` (
  `user_id` VARCHAR(32) NOT NULL,
  `grade` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `conversion_score` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `attendance_score` INT(10) UNSIGNED NOT NULL DEFAULT 15,
  `volunteer_score` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `final_score` DOUBLE GENERATED ALWAYS AS (conversion_score + attendance_score + volunteer_score),
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK_ged_grade_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`graduate_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`graduate_grade` (
  `user_id` VARCHAR(32) NOT NULL,
  `semester` INT(1) NOT NULL,
  `korean` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `social` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `history` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `math` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `science` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `tech` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `english` ENUM('A', 'B', 'C', 'D', 'E', 'F', 'X') NOT NULL DEFAULT 'X',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `semester`),
  CONSTRAINT `FK_grade_info_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`graduate_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`graduate_score` (
  `user_id` VARCHAR(32) NOT NULL,
  `first_grade` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `second_grade` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `third_grade` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `conversion_score` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `attendance_score` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `volunteer_score` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `final_score` DOUBLE GENERATED ALWAYS AS (conversion_score + attendance_score + volunteer_score),
  `volunteer_time` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `period_cut` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `full_cut` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `late` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `early_leave` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FK_graduate_grade_user_id_idx` (`user_id` ASC),
  CONSTRAINT `FK_graduate_grade_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`school` (
  `code` VARCHAR(10) NOT NULL,
  `government` VARCHAR(20) NULL DEFAULT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `school_region` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`graduate_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`graduate_info` (
  `user_id` VARCHAR(32) NOT NULL,
  `graduate_year` INT(10) UNSIGNED NOT NULL DEFAULT '2019',
  `school_code` VARCHAR(32) NOT NULL,
  `school_name` VARCHAR(50) NOT NULL DEFAULT '',
  `school_tel` VARCHAR(15) NOT NULL DEFAULT '',
  `student_class` INT(10) UNSIGNED NOT NULL,
  `student_grade` INT(10) UNSIGNED NOT NULL DEFAULT '3',
  `student_number` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FK_graduate_info_school_code` (`school_code` ASC),
  CONSTRAINT `FK_graduate_info_school_code`
    FOREIGN KEY (`school_code`)
    REFERENCES `entry`.`school` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_graduate_info_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`info` (
  `user_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `sex` ENUM('FEMALE', 'MALE') NULL,
  `birth` DATE NOT NULL,
  `my_tel` VARCHAR(15) NOT NULL DEFAULT '',
  `parent_name` VARCHAR(20) NOT NULL DEFAULT '',
  `parent_tel` VARCHAR(15) NOT NULL DEFAULT '',
  `address_base` VARCHAR(100) NOT NULL DEFAULT '',
  `address_detail` VARCHAR(50) NOT NULL DEFAULT '',
  `zip_code` VARCHAR(5) NOT NULL DEFAULT '',
  `img_path` VARCHAR(50) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `img_path_UNIQUE` (`img_path` ASC),
  CONSTRAINT `FK_info_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `entry`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `entry`.`temp_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entry`.`temp_user` (
  `code` VARCHAR(32) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `UK_user_email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
